### ISSUE TITLE
'BUFFER_LENGTH' was not declared in this scope

### ISSUE THREAD

**Issue by LongmontRobotics** [SV-Zanshin/MCP7940#34]
In file included from C:\Users\Donald\Documents\Arduino\libraries\MCP7940\examples\SquareWave\SquareWave.ino:37:0:

C:\Users\Donald\Documents\Arduino\libraries\MCP7940\src/MCP7940.h: In member function 'uint8_t& MCP7940_Class::readRAM(uint8_t, T&)':

C:\Users\Donald\Documents\Arduino\libraries\MCP7940\src/MCP7940.h:238:17: error: 'BUFFER_LENGTH' was not declared in this scope

           if (i%BUFFER_LENGTH==0) {                                           // Read I2C again on buffer boundary//

**Comment by SV-Zanshin** [comment]
I just tried to compile for an ESP32 (which I happened to purchase this weekend) and get the compiler error you mentioned. 
Unfortunately when I fixed that error, I received an error regarding the interrupt handling, which is done differently on the ESP32 than with Atmel chips.  I will fix this for the ESP32 but don't know if that is the microprocessor you are using.

**Comment by SV-Zanshin** [comment]
I've uploaded a new version of the SquareWave.ino program which should fix the interrupt issue.

**Comment by typetrade** [comment]
#if !defined(BUFFER_LENGTH)  // The ESP32 Wire library doesn't currently define BUFFER_LENGTH
  /** @brief If the "Wire.h" library doesn't define the buffer, do so here */
  #define BUFFER_LENGTH 32
#endif

**Comment by SV-Zanshin** [comment]
@typetrade - I'm not sure what your message means, it looks like you've pasted the source code from the current header file. But there's no comment and this issue was closed in 2018...
