### ISSUE TITLE
How to obtain power failure date/hour

### ISSUE THREAD

**Issue by sounox** [SV-Zanshin/MCP7940#48]
Hello ! 
First of all, thank you for this librairy !
In the documentation, it is said that the RTC memorize power outage time/ date and when the power comes back on, how do we obtain these times/dates ?

**Comment by SV-Zanshin** [comment]
Hello sounox,

The functions [getPowerDown()](https://github.com/SV-Zanshin/MCP7940/wiki/getPowerDown()) and [getPowerUp()](https://github.com/SV-Zanshin/MCP7940/wiki/getPowerUp()) will return those  date/time values to you.
