### ISSUE TITLE
Bug in begin()

### ISSUE THREAD

**Issue by dtran11** [SV-Zanshin/MCP7940#8]
I think this line:

writeByte(MCP7940_RTCSEC,readByte(MCP7940_RTCHOUR)&B10111111);

Should be

writeByte(MCP7940_RTCHOUR,readByte(MCP7940_RTCHOUR)&B10111111);

Thanks for the project.

**Comment by SV-Zanshin** [comment]
Thanks for noting that - I missed that small, but important, error.

**Comment by SV-Zanshin** [comment]
Fixed in Release 1.0.5b
